### PR TITLE
Updates to requirements and BeautifulSoup init

### PR DESCRIPTION
**Pull request by tophertimzen**
Adding ply==3.4 to requirements.txt for slimit and "html.parser" in BeautifulSoup4 init to avoid error messages.

### CODE REVIEW

**Comment by iheanyi** [comment]
Good looks :+1: There are some merge conflicts but I'll see what the deal with those are. Thanks for your contribution!

**Comment by tophertimzen** [comment]
Odd, didn't notice that. Doesn't look like it should, though.

**Comment by iheanyi** [comment]
@tophertimzen - Did you ever figure out the merge conflicts for this pull request?

**Comment by tophertimzen** [comment]
I did and they are due to the fact I was trying to slim the repository size from 85 MB. I will close this pull request. Please look into issue https://github.com/iheanyi/bandcamp-dl/issues/29

**Pull request closed without merging**
