### PR TITLE
Using api

### PR DESCRIPTION
**Pull request by JBKahn**
For your consideration, a less brittle appraoch than parsing the request, is to use the api.
I don't have an api key at the moment so I was just using the one in the api docs. It makes the code pretty simple as well as allowing you to download whole artist discography if available. Check it out.

### CODE REVIEW

**Comment by iheanyi** [comment]
@JBKahn - I know that there's an API key floating from their docs, but I do not want to an API key that does not belong to me, so I can't accept that pull request.

**Comment by JBKahn** [comment]
I don't intend for it to be merged without one.

**Comment by iheanyi** [comment]
@JBKahn - Yeah, the problem with Bandcamp is that they aren't handing out Developer API keys anymore. ~___~

**Comment by JBKahn** [comment]
It's not ready for merging as of yet anyway. It works on the 3 artists I've tested but I still need to do more testing and try to acquire a key.

**Comment by JBKahn** [comment]
ahhhh I didn't know that. I've never user their API before. That sucks. Well I'll continue to use this branch myself anyway for personal use but if I ever get a key then maybe it'll make it to master

**Pull request closed without merging**
